### PR TITLE
add target to run static analyzer

### PR DESCRIPTION
**Pull request by wtholliday**
Adds a target to run the static analyzer, revealing various warnings.

Would love to hear your thoughts on how to fix :)

### CODE REVIEW

**Comment by PaulBatchelor** [comment]
Oh this is a neat feature. Thanks for this!

These seem to mostly be complaints about variables being never read. In certain modes like `PLUMBER_CREATE` and `PLUMBER_INIT`, I'd often pop and store stuff in variables rather than cast away the return variable. For the most part, I think these are harmless. Would be nice to clean up at some point though.

Looks like it uncovered some undefined behavior in the new function I added `plumber_sp_process`, which was a function I ported from and older version of Soundpipe to keep Sporth running. `sp_process` was one of the oldest soundpipe functions, and it has hardly changed much since it was written.

**Comment by wtholliday** [comment]
@PaulBatchelor I was thinking of adding something like `sporth_stack_pop(stack, "ffff")` to pop multiple args. Could even combine `sporth_check_args` with popping. But there are cases, like in `sporth_osc` where the `PLUMBER_CREATE` phase does need the values from the stack. So the scripts which generate these files would have to account for that.

**Comment by PaulBatchelor** [comment]
@wtholliday if you want to build it, I'll merge it.

**Comment by wtholliday** [comment]
@PaulBatchelor will do. How do I validate my changes? I don't see a tests target.

**Comment by PaulBatchelor** [comment]
@wtholliday Well, other than building test patches for the particular ugen(s) you are changing, I'm afraid there isn't anything you can do for verification, formal or otherwise.

You have my promise that if you do break anything, I'll take it out of my paycheck, and not yours ;)

**Comment by wtholliday** [comment]
@PaulBatchelor haha :)  What if I added md5s for all the examples?

**Comment by PaulBatchelor** [comment]
@wtholliday that would be a step in the right direction. You could probably rig something quick and dirty with a shell script. For example

```
./sporth -b raw examples/dialtone.sp | md5sum
4ec984e80addbbef6a77e99d1029a726  -
```
Which is basically doing what the soundpipe tests are doing.

With any luck, that hash should be the same on every platform.

Fair warning, I've been neglecting Sporth, and not all the examples work now due to changes in Soundpipe. Most of the time, this is because I disabled ugens, so they will break quite angrily. I don't anticipate many problems beyond that. Of the bits of Soundpipe that do remain, the behavior is very much the same.

**Pull request merged**
