### PR TITLE
Zitarev naming typo

### PR DESCRIPTION
**Pull request by aure**
Not sure how this passed your tests, but I needed to make this change to be able to compile.

### CODE REVIEW

**Comment by PaulBatchelor** [comment]
I did some tweaks this morning. Pull the latest Soundpipe. this shouldn't be necessary.

**Comment by aure** [comment]
Sorry, just kinda got lost in all my branches and forks, I'm just going to be working off your branch from now on.

**Comment by aure** [comment]
On the other hand, is there a reason why its flipping back and forth?  want to choose one?

**Comment by PaulBatchelor** [comment]
The flip happened accidentally when cleaning up the Faust DSP file. I didn't notice it until I was done with the conversion. 

It takes a bit of work to go back and make tweaks, but I'm happy to do so if you have a strong preference.

**Pull request closed without merging**
