### PR TITLE
allow for line continuation via backslash, which is helpful for thing…

### PR DESCRIPTION
**Pull request by akjmicro**
…s like long sequence definitions

### CODE REVIEW

**Comment by PaulBatchelor** [comment]
I'm always very cautious when tampering with the part of the code dealing with the parser, but I think this is okay. It works, and it is helpful. 

One thing I will mention is that other users may think that the backslash can be used for escape characters like other languages. For instance, someone may see your example patch and try `"\"hello world\"" say 0` only to be greeted with a syntax error. Since Sporth strings have rather limited functionality to begin with (and also since it would require a great deal more work to do right), it is a weird quirk I'm happy to live with.

**Comment by akjmicro** [comment]
Yes, cool.

Agreed re:escape strings. It can be on a TODO list.

-A.

P.S. I have a PR for a small feature add for both soundpipe and sporth:
mtof_edoC and mtof_edoA, ways to allow access to N-equal octave division
microtonal pitches based on either A440 or C261, using either midi key 69
or midi key 60 as a central anchor point.

**Comment by PaulBatchelor** [comment]
> P.S. I have a PR for a small feature add for both soundpipe and sporth:
mtof_edoC and mtof_edoA, ways to allow access to N-equal octave division
microtonal pitches based on either A440 or C261, using either midi key 69
or midi key 60 as a central anchor point.

You are welcome to submit a PR to Sporth. If you do so, I would request that you generalize it more such that each part of the equation can have a variable. 

I'm afraid I'm going to have to nix it for Soundpipe. It's just not within the narrow scope of Soundpipe. 

Specifically, here are my reasons:

1. It's conversion function, which to me does not qualify as a Soundpipe DSP module. There are exceptions that you'll find in Soundpipe, such as those you find in base.c. However, these are older parts of the code. You'll notice that Sporth has conversion functions like ampdb which do not exist in Soundpipe. 

2. It's too specific a microtonality function. I can't just having that be the *only* microtonal thing Soundpipe does. That being said, I also can't justify having every microtonal scale and idea in existence. It wouldn't be Soundpipe anymore. The world of microtonal/alternate tunings is way too vast: it would completely overpower the library.

What I dream of is a nice small dedicated ANSI C library just for microtonality and alternative tunings. Something that could interface with Soundpipe/Sporth easily.

**Comment by akjmicro** [comment]
Got it...the reason I was working in both soundpipe and sporth is that you
leverage 'midi2cps' for 'mtof'. You need a more general soundpipe function
that isn't tied to 12edo, or as you said, keep it local to Sporth, which I
am happy to do, but it would be using similar conversion code.

I'm also fine helping drum up a tuning and microtonality library, something
that would be able to read scala .scl files, etc.

-AKJ

**Comment by akjmicro** [comment]
Just sent you a merge request for a new 'edo' ugen.

While I'm thinking of it, I think it would be neat to have something along
the lines of 'prop' for composing scores, but along the more general lines
of the philosophy behind my 'microcsound' score format: an ASCII string
interpreter that would allow easy specification of multiple parameter
streams (per voice or for a single voice) at once, i.e. one wouldn't have
to specify pitch, amplitude, timing info, etc. in several different GEN
tables manually, but the parser for such a ugen would automatically break
them into such streams and push them to the stack to be consumed by
whatever ugen. The number of parameters output would be of course specified
in the string itself.

This would allow a composer to easily use Sporth to compose: all the
parameters they are concerned with would be local to the ASCII
representation of the voice/note event: how long it is held, what is its
articulation, attack volume, pitch, and any number of arbitrary parameters
that would also be specified as well. That number would remain constant
over the lifetime of the parsed string, and would determine the number of
SPFLOAT stack items that would be pushed.

I'm thinking of the kind of work I did with microcsound, but it could be
simplified, adapted, or generalized/evolved for Sporth.

e.g.:

"1: t=60 1/4 0 2 4 5 7 9 11 12 t 1/8 11 9 .7 .5 1/2 .4 .2 0 t -12 t t"

would translate to (assuming normal 12edo): Voice 1 is: Q=60 BPM; 1/4 note
ascending major scale, middle-C to C above that, switch to 1/8 notes,
descend, staccato on the next four notes, but switch to 1/2 notes midway,
last note in normal non-legato articulation, double in length ('t' would
mean 'tie'), then go down to C below middle-C (-12), tie it twice...

The point being that timing, notes, articulation would all be in one place,
the program does the work to split it into private tables that it uses to
sequence as separate stack elements to be consumed by some ugen instrument,
instead of manually having to split that work out (makes it hard to debug
and keep track of the separate streams, and takes more time.

The ideas are more fleshed out a t
http://untwelve.org/static/microcsound/tutorial.txt but I wasn't even
thinking of letter notation, per se (although that could be done) but
keeping it numerical for now...

-AKJ





Aaron Krister Johnson
http://www.untwelve.org

**Comment by PaulBatchelor** [comment]
Seems like an interesting idea, but one thing I will say is that Sporth is not built to handle concepts like "notes", "events in time", or "polyphony", much in the same way hardware modular rigs such as eurorack do not really support those as well. This is a sharp contrast to Csound, where such concepts are built at the core of the language. The more Sporthful approach would be to mix articulated signals that can be combined and layered together to form evolving textures that could be described as being "polyphonic" or "polysonic".

**Comment by akjmicro** [comment]
Yes, I see. Well, perhaps a way to still define a monophonic line that
combines various strands of parametric data "in one place" (a unified
string), as a shortcut tool that might address common use cases such as
having to otherwise manually define e.g. pitch, time, and attack in their
own tables, for instance?

Understood if that isn't a route you'd want to go down either, i.e., you'd
prefer that every signal is arbitrarily wide-open and should be more
"manual".

One middle-road approach might be to allow OSC and/or MIDI communication to
establish external control signals...this would allow a more score-like
approach to be indirectly accomodated, at least, by allowing a traditional
MIDI sequencer handle such things.

**Pull request merged**
